# P2P Tunnel Client Configuration

spring:
  application:
    name: p2p-tunnel-client

logging:
  level:
    root: INFO
    com.tyin.zero: DEBUG
    com.tyin.zero.p2pcommon.protocol.TunnelMessageCodec: INFO
    com.tyin.zero.p2pcommon.p2p.P2pUdpCodec: INFO
  file:
    name: logs/p2p-client.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"